import fs from "fs";
import path from "path";

const projectRoot = process.cwd();
const wgslDir = path.join(projectRoot, "wgsl");

const computePath = path.join(wgslDir, "compute_template.wgsl");
const vertexPath = path.join(wgslDir, "vertex_template.wgsl");
const keyframeMathPath = path.join(wgslDir, "keyframe_math.wgsl");

const computeWgsl = fs.readFileSync(computePath, "utf-8");
const vertexWgsl = fs.readFileSync(vertexPath, "utf-8");
const keyframeMathWgsl = fs.readFileSync(keyframeMathPath, "utf-8");

const fileContent = `// Auto-generated by scripts/embed-shaders.ts. DO NOT EDIT DIRECTLY.

export const COMPUTE_TEMPLATE: string = ${JSON.stringify(computeWgsl)};
export const VERTEX_TEMPLATE: string = ${JSON.stringify(vertexWgsl)};
export const KEYFRAME_MATH: string = ${JSON.stringify(keyframeMathWgsl)};
`;

const targets = [
  path.join(projectRoot, "packages", "webgpu", "src", "generated", "shaders.ts"),
  path.join(projectRoot, "js", "generated", "shaders.ts"),
];

for (const target of targets) {
  const dir = path.dirname(target);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(target, fileContent, "utf-8");
  console.log(`Generated embedded WGSL shaders at ${path.relative(projectRoot, target)}`);
}
